// Commented out to avoid build errors - uncomment when needed for seeding
// import mongoose from 'mongoose';
// import dotenv from 'dotenv';
// import Food from '../models/Food.model';

// dotenv.config();

export const comprehensiveFoods = [
  // PROTEINS - Meat & Poultry
  {
    name: 'Chicken Breast',
    category: 'Protein',
    servingSize: 100,
    servingUnit: 'grams',
    nutrition: {
      calories: 165,
      protein: 31,
      carbs: 0,
      fat: 3.6,
      fiber: 0,
      sugar: 0,
      sodium: 74,
      calcium: 15,
      iron: 1,
      vitaminA: 21,
      vitaminC: 0,
      vitaminD: 0.1,
    },
    description: 'Skinless, boneless chicken breast, grilled',
  },
  {
    name: 'Chicken Thigh',
    category: 'Protein',
    servingSize: 100,
    servingUnit: 'grams',
    nutrition: {
      calories: 209,
      protein: 26,
      carbs: 0,
      fat: 10.9,
      fiber: 0,
      sugar: 0,
      sodium: 95,
      calcium: 11,
      iron: 1.3,
      vitaminA: 60,
      vitaminC: 0,
      vitaminD: 0.2,
    },
    description: 'Skinless chicken thigh, cooked',
  },
  {
    name: 'Ground Beef (90% lean)',
    category: 'Protein',
    servingSize: 100,
    servingUnit: 'grams',
    nutrition: {
      calories: 176,
      protein: 25,
      carbs: 0,
      fat: 8,
      fiber: 0,
      sugar: 0,
      sodium: 72,
      calcium: 18,
      iron: 2.5,
      vitaminA: 0,
      vitaminC: 0,
      vitaminD: 0.1,
    },
    description: 'Lean ground beef, cooked',
  },
  {
    name: 'Turkey Breast',
    category: 'Protein',
    servingSize: 100,
    servingUnit: 'grams',
    nutrition: {
      calories: 135,
      protein: 30,
      carbs: 0,
      fat: 0.7,
      fiber: 0,
      sugar: 0,
      sodium: 55,
      calcium: 4,
      iron: 1.4,
      vitaminA: 0,
      vitaminC: 0,
      vitaminD: 0,
    },
    description: 'Skinless turkey breast, roasted',
  },
  {
    name: 'Pork Tenderloin',
    category: 'Protein',
    servingSize: 100,
    servingUnit: 'grams',
    nutrition: {
      calories: 143,
      protein: 26,
      carbs: 0,
      fat: 3.5,
      fiber: 0,
      sugar: 0,
      sodium: 62,
      calcium: 6,
      iron: 1.4,
      vitaminA: 2,
      vitaminC: 0.5,
      vitaminD: 0.5,
    },
    description: 'Lean pork tenderloin, roasted',
  },

  // PROTEINS - Seafood
  {
    name: 'Salmon',
    category: 'Protein',
    servingSize: 100,
    servingUnit: 'grams',
    nutrition: {
      calories: 208,
      protein: 20,
      carbs: 0,
      fat: 13,
      fiber: 0,
      sugar: 0,
      sodium: 59,
      calcium: 9,
      iron: 0.3,
      vitaminA: 40,
      vitaminC: 0,
      vitaminD: 11,
    },
    description: 'Atlantic salmon, cooked',
  },
  {
    name: 'Tuna',
    category: 'Protein',
    servingSize: 100,
    servingUnit: 'grams',
    nutrition: {
      calories: 132,
      protein: 28,
      carbs: 0,
      fat: 1.3,
      fiber: 0,
      sugar: 0,
      sodium: 47,
      calcium: 10,
      iron: 1.3,
      vitaminA: 16,
      vitaminC: 0,
      vitaminD: 5.7,
    },
    description: 'Yellowfin tuna, cooked',
  },
  {
    name: 'Shrimp',
    category: 'Protein',
    servingSize: 100,
    servingUnit: 'grams',
    nutrition: {
      calories: 99,
      protein: 24,
      carbs: 0.2,
      fat: 0.3,
      fiber: 0,
      sugar: 0,
      sodium: 111,
      calcium: 70,
      iron: 0.5,
      vitaminA: 54,
      vitaminC: 2,
      vitaminD: 0,
    },
    description: 'Cooked shrimp',
  },
  {
    name: 'Cod',
    category: 'Protein',
    servingSize: 100,
    servingUnit: 'grams',
    nutrition: {
      calories: 105,
      protein: 23,
      carbs: 0,
      fat: 0.9,
      fiber: 0,
      sugar: 0,
      sodium: 78,
      calcium: 18,
      iron: 0.5,
      vitaminA: 14,
      vitaminC: 1,
      vitaminD: 1.2,
    },
    description: 'Atlantic cod, cooked',
  },
  {
    name: 'Tilapia',
    category: 'Protein',
    servingSize: 100,
    servingUnit: 'grams',
    nutrition: {
      calories: 128,
      protein: 26,
      carbs: 0,
      fat: 2.7,
      fiber: 0,
      sugar: 0,
      sodium: 52,
      calcium: 14,
      iron: 0.7,
      vitaminA: 0,
      vitaminC: 0,
      vitaminD: 3.1,
    },
    description: 'Tilapia fillet, cooked',
  },

  // PROTEINS - Eggs & Dairy
  {
    name: 'Eggs',
    category: 'Protein',
    servingSize: 50,
    servingUnit: 'grams',
    nutrition: {
      calories: 72,
      protein: 6,
      carbs: 0.4,
      fat: 5,
      fiber: 0,
      sugar: 0.2,
      sodium: 71,
      calcium: 28,
      iron: 0.9,
      vitaminA: 270,
      vitaminC: 0,
      vitaminD: 2,
    },
    description: 'Large whole egg',
  },
  {
    name: 'Egg Whites',
    category: 'Protein',
    servingSize: 33,
    servingUnit: 'grams',
    nutrition: {
      calories: 17,
      protein: 3.6,
      carbs: 0.2,
      fat: 0.1,
      fiber: 0,
      sugar: 0.2,
      sodium: 55,
      calcium: 2,
      iron: 0,
      vitaminA: 0,
      vitaminC: 0,
      vitaminD: 0,
    },
    description: 'Egg white only',
  },
  {
    name: 'Greek Yogurt',
    category: 'Dairy',
    servingSize: 100,
    servingUnit: 'grams',
    nutrition: {
      calories: 59,
      protein: 10,
      carbs: 3.6,
      fat: 0.4,
      fiber: 0,
      sugar: 3.2,
      sodium: 36,
      calcium: 110,
      iron: 0,
      vitaminA: 0,
      vitaminC: 0.8,
      vitaminD: 0,
    },
    description: 'Plain, non-fat Greek yogurt',
  },
  {
    name: 'Cottage Cheese',
    category: 'Dairy',
    servingSize: 100,
    servingUnit: 'grams',
    nutrition: {
      calories: 98,
      protein: 11,
      carbs: 3.4,
      fat: 4.3,
      fiber: 0,
      sugar: 2.7,
      sodium: 364,
      calcium: 83,
      iron: 0.1,
      vitaminA: 140,
      vitaminC: 0,
      vitaminD: 0,
    },
    description: 'Low-fat cottage cheese',
  },
  {
    name: 'Cheddar Cheese',
    category: 'Dairy',
    servingSize: 28,
    servingUnit: 'grams',
    nutrition: {
      calories: 113,
      protein: 7,
      carbs: 0.4,
      fat: 9,
      fiber: 0,
      sugar: 0.1,
      sodium: 174,
      calcium: 200,
      iron: 0.2,
      vitaminA: 284,
      vitaminC: 0,
      vitaminD: 0.2,
    },
    description: 'Sharp cheddar cheese',
  },
  {
    name: 'Milk (2%)',
    category: 'Dairy',
    servingSize: 244,
    servingUnit: 'ml',
    nutrition: {
      calories: 122,
      protein: 8,
      carbs: 12,
      fat: 5,
      fiber: 0,
      sugar: 12,
      sodium: 115,
      calcium: 293,
      iron: 0,
      vitaminA: 134,
      vitaminC: 0,
      vitaminD: 2.9,
    },
    description: '2% reduced fat milk',
  },

  // GRAINS & CARBS
  {
    name: 'Brown Rice',
    category: 'Grains',
    servingSize: 100,
    servingUnit: 'grams',
    nutrition: {
      calories: 112,
      protein: 2.6,
      carbs: 24,
      fat: 0.9,
      fiber: 1.8,
      sugar: 0.4,
      sodium: 5,
      calcium: 10,
      iron: 0.4,
      vitaminA: 0,
      vitaminC: 0,
      vitaminD: 0,
    },
    description: 'Cooked brown rice',
  },
  {
    name: 'White Rice',
    category: 'Grains',
    servingSize: 100,
    servingUnit: 'grams',
    nutrition: {
      calories: 130,
      protein: 2.7,
      carbs: 28,
      fat: 0.3,
      fiber: 0.4,
      sugar: 0.1,
      sodium: 1,
      calcium: 10,
      iron: 0.2,
      vitaminA: 0,
      vitaminC: 0,
      vitaminD: 0,
    },
    description: 'Cooked white rice',
  },
  {
    name: 'Quinoa',
    category: 'Grains',
    servingSize: 100,
    servingUnit: 'grams',
    nutrition: {
      calories: 120,
      protein: 4.4,
      carbs: 21,
      fat: 1.9,
      fiber: 2.8,
      sugar: 0.9,
      sodium: 7,
      calcium: 17,
      iron: 1.5,
      vitaminA: 5,
      vitaminC: 0,
      vitaminD: 0,
    },
    description: 'Cooked quinoa',
  },
  {
    name: 'Oatmeal',
    category: 'Grains',
    servingSize: 100,
    servingUnit: 'grams',
    nutrition: {
      calories: 71,
      protein: 2.5,
      carbs: 12,
      fat: 1.5,
      fiber: 1.7,
      sugar: 0.3,
      sodium: 49,
      calcium: 9,
      iron: 1,
      vitaminA: 0,
      vitaminC: 0,
      vitaminD: 0,
    },
    description: 'Cooked oatmeal',
  },
  {
    name: 'Whole Wheat Bread',
    category: 'Grains',
    servingSize: 28,
    servingUnit: 'grams',
    nutrition: {
      calories: 69,
      protein: 3.6,
      carbs: 11.6,
      fat: 1.2,
      fiber: 1.9,
      sugar: 1.4,
      sodium: 132,
      calcium: 24,
      iron: 0.9,
      vitaminA: 0,
      vitaminC: 0,
      vitaminD: 0,
    },
    description: 'Whole wheat bread slice',
  },
  {
    name: 'Whole Wheat Pasta',
    category: 'Grains',
    servingSize: 100,
    servingUnit: 'grams',
    nutrition: {
      calories: 124,
      protein: 5.3,
      carbs: 26,
      fat: 0.5,
      fiber: 3.9,
      sugar: 0.8,
      sodium: 3,
      calcium: 15,
      iron: 1.3,
      vitaminA: 0,
      vitaminC: 0,
      vitaminD: 0,
    },
    description: 'Cooked whole wheat pasta',
  },
  {
    name: 'Bagel',
    category: 'Grains',
    servingSize: 89,
    servingUnit: 'grams',
    nutrition: {
      calories: 245,
      protein: 10,
      carbs: 48,
      fat: 1.4,
      fiber: 1.9,
      sugar: 5.3,
      sodium: 430,
      calcium: 13,
      iron: 3.2,
      vitaminA: 0,
      vitaminC: 0,
      vitaminD: 0,
    },
    description: 'Plain bagel',
  },

  // VEGETABLES
  {
    name: 'Broccoli',
    category: 'Vegetables',
    servingSize: 100,
    servingUnit: 'grams',
    nutrition: {
      calories: 34,
      protein: 2.8,
      carbs: 7,
      fat: 0.4,
      fiber: 2.6,
      sugar: 1.7,
      sodium: 33,
      calcium: 47,
      iron: 0.7,
      vitaminA: 623,
      vitaminC: 89,
      vitaminD: 0,
    },
    description: 'Fresh broccoli',
  },
  {
    name: 'Spinach',
    category: 'Vegetables',
    servingSize: 100,
    servingUnit: 'grams',
    nutrition: {
      calories: 23,
      protein: 2.9,
      carbs: 3.6,
      fat: 0.4,
      fiber: 2.2,
      sugar: 0.4,
      sodium: 79,
      calcium: 99,
      iron: 2.7,
      vitaminA: 9377,
      vitaminC: 28,
      vitaminD: 0,
    },
    description: 'Fresh spinach',
  },
  {
    name: 'Sweet Potato',
    category: 'Vegetables',
    servingSize: 100,
    servingUnit: 'grams',
    nutrition: {
      calories: 86,
      protein: 1.6,
      carbs: 20,
      fat: 0.1,
      fiber: 3,
      sugar: 4.2,
      sodium: 55,
      calcium: 30,
      iron: 0.6,
      vitaminA: 14187,
      vitaminC: 2.4,
      vitaminD: 0,
    },
    description: 'Baked sweet potato',
  },
  {
    name: 'Carrots',
    category: 'Vegetables',
    servingSize: 100,
    servingUnit: 'grams',
    nutrition: {
      calories: 41,
      protein: 0.9,
      carbs: 10,
      fat: 0.2,
      fiber: 2.8,
      sugar: 4.7,
      sodium: 69,
      calcium: 33,
      iron: 0.3,
      vitaminA: 16706,
      vitaminC: 5.9,
      vitaminD: 0,
    },
    description: 'Raw carrots',
  },
  {
    name: 'Bell Pepper',
    category: 'Vegetables',
    servingSize: 100,
    servingUnit: 'grams',
    nutrition: {
      calories: 31,
      protein: 1,
      carbs: 6,
      fat: 0.3,
      fiber: 2.1,
      sugar: 4.2,
      sodium: 4,
      calcium: 7,
      iron: 0.4,
      vitaminA: 3131,
      vitaminC: 128,
      vitaminD: 0,
    },
    description: 'Red bell pepper',
  },
  {
    name: 'Tomato',
    category: 'Vegetables',
    servingSize: 100,
    servingUnit: 'grams',
    nutrition: {
      calories: 18,
      protein: 0.9,
      carbs: 3.9,
      fat: 0.2,
      fiber: 1.2,
      sugar: 2.6,
      sodium: 5,
      calcium: 10,
      iron: 0.3,
      vitaminA: 833,
      vitaminC: 14,
      vitaminD: 0,
    },
    description: 'Fresh tomato',
  },
  {
    name: 'Cucumber',
    category: 'Vegetables',
    servingSize: 100,
    servingUnit: 'grams',
    nutrition: {
      calories: 15,
      protein: 0.7,
      carbs: 3.6,
      fat: 0.1,
      fiber: 0.5,
      sugar: 1.7,
      sodium: 2,
      calcium: 16,
      iron: 0.3,
      vitaminA: 105,
      vitaminC: 2.8,
      vitaminD: 0,
    },
    description: 'Fresh cucumber with peel',
  },
  {
    name: 'Lettuce',
    category: 'Vegetables',
    servingSize: 100,
    servingUnit: 'grams',
    nutrition: {
      calories: 15,
      protein: 1.4,
      carbs: 2.9,
      fat: 0.2,
      fiber: 1.3,
      sugar: 0.8,
      sodium: 28,
      calcium: 36,
      iron: 0.9,
      vitaminA: 7405,
      vitaminC: 9.2,
      vitaminD: 0,
    },
    description: 'Romaine lettuce',
  },
  {
    name: 'Cauliflower',
    category: 'Vegetables',
    servingSize: 100,
    servingUnit: 'grams',
    nutrition: {
      calories: 25,
      protein: 1.9,
      carbs: 5,
      fat: 0.3,
      fiber: 2,
      sugar: 1.9,
      sodium: 30,
      calcium: 22,
      iron: 0.4,
      vitaminA: 0,
      vitaminC: 48,
      vitaminD: 0,
    },
    description: 'Raw cauliflower',
  },
  {
    name: 'Zucchini',
    category: 'Vegetables',
    servingSize: 100,
    servingUnit: 'grams',
    nutrition: {
      calories: 17,
      protein: 1.2,
      carbs: 3.1,
      fat: 0.3,
      fiber: 1,
      sugar: 2.5,
      sodium: 8,
      calcium: 16,
      iron: 0.4,
      vitaminA: 200,
      vitaminC: 17.9,
      vitaminD: 0,
    },
    description: 'Raw zucchini',
  },

  // FRUITS
  {
    name: 'Banana',
    category: 'Fruits',
    servingSize: 100,
    servingUnit: 'grams',
    nutrition: {
      calories: 89,
      protein: 1.1,
      carbs: 23,
      fat: 0.3,
      fiber: 2.6,
      sugar: 12,
      sodium: 1,
      calcium: 5,
      iron: 0.3,
      vitaminA: 64,
      vitaminC: 8.7,
      vitaminD: 0,
    },
    description: 'Fresh banana',
  },
  {
    name: 'Apple',
    category: 'Fruits',
    servingSize: 100,
    servingUnit: 'grams',
    nutrition: {
      calories: 52,
      protein: 0.3,
      carbs: 14,
      fat: 0.2,
      fiber: 2.4,
      sugar: 10,
      sodium: 1,
      calcium: 6,
      iron: 0.1,
      vitaminA: 54,
      vitaminC: 4.6,
      vitaminD: 0,
    },
    description: 'Fresh apple with skin',
  },
  {
    name: 'Orange',
    category: 'Fruits',
    servingSize: 100,
    servingUnit: 'grams',
    nutrition: {
      calories: 47,
      protein: 0.9,
      carbs: 12,
      fat: 0.1,
      fiber: 2.4,
      sugar: 9,
      sodium: 0,
      calcium: 40,
      iron: 0.1,
      vitaminA: 225,
      vitaminC: 53,
      vitaminD: 0,
    },
    description: 'Fresh orange',
  },
  {
    name: 'Strawberries',
    category: 'Fruits',
    servingSize: 100,
    servingUnit: 'grams',
    nutrition: {
      calories: 32,
      protein: 0.7,
      carbs: 7.7,
      fat: 0.3,
      fiber: 2,
      sugar: 4.9,
      sodium: 1,
      calcium: 16,
      iron: 0.4,
      vitaminA: 12,
      vitaminC: 59,
      vitaminD: 0,
    },
    description: 'Fresh strawberries',
  },
  {
    name: 'Blueberries',
    category: 'Fruits',
    servingSize: 100,
    servingUnit: 'grams',
    nutrition: {
      calories: 57,
      protein: 0.7,
      carbs: 14,
      fat: 0.3,
      fiber: 2.4,
      sugar: 10,
      sodium: 1,
      calcium: 6,
      iron: 0.3,
      vitaminA: 54,
      vitaminC: 9.7,
      vitaminD: 0,
    },
    description: 'Fresh blueberries',
  },
  {
    name: 'Avocado',
    category: 'Fruits',
    servingSize: 100,
    servingUnit: 'grams',
    nutrition: {
      calories: 160,
      protein: 2,
      carbs: 9,
      fat: 15,
      fiber: 7,
      sugar: 0.7,
      sodium: 7,
      calcium: 12,
      iron: 0.6,
      vitaminA: 146,
      vitaminC: 10,
      vitaminD: 0,
    },
    description: 'Fresh avocado',
  },
  {
    name: 'Grapes',
    category: 'Fruits',
    servingSize: 100,
    servingUnit: 'grams',
    nutrition: {
      calories: 69,
      protein: 0.7,
      carbs: 18,
      fat: 0.2,
      fiber: 0.9,
      sugar: 15,
      sodium: 2,
      calcium: 10,
      iron: 0.4,
      vitaminA: 66,
      vitaminC: 3.2,
      vitaminD: 0,
    },
    description: 'Fresh grapes',
  },
  {
    name: 'Watermelon',
    category: 'Fruits',
    servingSize: 100,
    servingUnit: 'grams',
    nutrition: {
      calories: 30,
      protein: 0.6,
      carbs: 8,
      fat: 0.2,
      fiber: 0.4,
      sugar: 6,
      sodium: 1,
      calcium: 7,
      iron: 0.2,
      vitaminA: 569,
      vitaminC: 8.1,
      vitaminD: 0,
    },
    description: 'Fresh watermelon',
  },
  {
    name: 'Mango',
    category: 'Fruits',
    servingSize: 100,
    servingUnit: 'grams',
    nutrition: {
      calories: 60,
      protein: 0.8,
      carbs: 15,
      fat: 0.4,
      fiber: 1.6,
      sugar: 14,
      sodium: 1,
      calcium: 11,
      iron: 0.2,
      vitaminA: 1082,
      vitaminC: 36,
      vitaminD: 0,
    },
    description: 'Fresh mango',
  },
  {
    name: 'Pineapple',
    category: 'Fruits',
    servingSize: 100,
    servingUnit: 'grams',
    nutrition: {
      calories: 50,
      protein: 0.5,
      carbs: 13,
      fat: 0.1,
      fiber: 1.4,
      sugar: 10,
      sodium: 1,
      calcium: 13,
      iron: 0.3,
      vitaminA: 58,
      vitaminC: 48,
      vitaminD: 0,
    },
    description: 'Fresh pineapple',
  },

  // NUTS & SEEDS
  {
    name: 'Almonds',
    category: 'Nuts & Seeds',
    servingSize: 28,
    servingUnit: 'grams',
    nutrition: {
      calories: 164,
      protein: 6,
      carbs: 6,
      fat: 14,
      fiber: 3.5,
      sugar: 1.2,
      sodium: 0,
      calcium: 76,
      iron: 1,
      vitaminA: 0,
      vitaminC: 0,
      vitaminD: 0,
    },
    description: 'Raw almonds',
  },
  {
    name: 'Walnuts',
    category: 'Nuts & Seeds',
    servingSize: 28,
    servingUnit: 'grams',
    nutrition: {
      calories: 185,
      protein: 4.3,
      carbs: 3.9,
      fat: 18.5,
      fiber: 1.9,
      sugar: 0.7,
      sodium: 1,
      calcium: 28,
      iron: 0.8,
      vitaminA: 6,
      vitaminC: 0.4,
      vitaminD: 0,
    },
    description: 'Raw walnuts',
  },
  {
    name: 'Peanut Butter',
    category: 'Nuts & Seeds',
    servingSize: 32,
    servingUnit: 'grams',
    nutrition: {
      calories: 188,
      protein: 8,
      carbs: 7,
      fat: 16,
      fiber: 2,
      sugar: 3,
      sodium: 147,
      calcium: 17,
      iron: 0.6,
      vitaminA: 0,
      vitaminC: 0,
      vitaminD: 0,
    },
    description: 'Smooth peanut butter',
  },
  {
    name: 'Cashews',
    category: 'Nuts & Seeds',
    servingSize: 28,
    servingUnit: 'grams',
    nutrition: {
      calories: 157,
      protein: 5,
      carbs: 9,
      fat: 12,
      fiber: 0.9,
      sugar: 1.7,
      sodium: 3,
      calcium: 10,
      iron: 1.9,
      vitaminA: 0,
      vitaminC: 0.1,
      vitaminD: 0,
    },
    description: 'Raw cashews',
  },
  {
    name: 'Chia Seeds',
    category: 'Nuts & Seeds',
    servingSize: 28,
    servingUnit: 'grams',
    nutrition: {
      calories: 138,
      protein: 4.7,
      carbs: 12,
      fat: 8.7,
      fiber: 9.8,
      sugar: 0,
      sodium: 5,
      calcium: 179,
      iron: 2.2,
      vitaminA: 15,
      vitaminC: 0.5,
      vitaminD: 0,
    },
    description: 'Chia seeds',
  },
  {
    name: 'Flaxseeds',
    category: 'Nuts & Seeds',
    servingSize: 10,
    servingUnit: 'grams',
    nutrition: {
      calories: 55,
      protein: 1.9,
      carbs: 3,
      fat: 4.3,
      fiber: 2.8,
      sugar: 0.2,
      sodium: 3,
      calcium: 26,
      iron: 0.6,
      vitaminA: 0,
      vitaminC: 0.1,
      vitaminD: 0,
    },
    description: 'Ground flaxseeds',
  },

  // LEGUMES
  {
    name: 'Lentils',
    category: 'Legumes',
    servingSize: 100,
    servingUnit: 'grams',
    nutrition: {
      calories: 116,
      protein: 9,
      carbs: 20,
      fat: 0.4,
      fiber: 7.9,
      sugar: 1.8,
      sodium: 2,
      calcium: 19,
      iron: 3.3,
      vitaminA: 8,
      vitaminC: 1.5,
      vitaminD: 0,
    },
    description: 'Cooked lentils',
  },
  {
    name: 'Black Beans',
    category: 'Legumes',
    servingSize: 100,
    servingUnit: 'grams',
    nutrition: {
      calories: 132,
      protein: 8.9,
      carbs: 24,
      fat: 0.5,
      fiber: 8.7,
      sugar: 0.3,
      sodium: 2,
      calcium: 27,
      iron: 2.1,
      vitaminA: 3,
      vitaminC: 0,
      vitaminD: 0,
    },
    description: 'Cooked black beans',
  },
  {
    name: 'Chickpeas',
    category: 'Legumes',
    servingSize: 100,
    servingUnit: 'grams',
    nutrition: {
      calories: 164,
      protein: 8.9,
      carbs: 27,
      fat: 2.6,
      fiber: 7.6,
      sugar: 4.8,
      sodium: 7,
      calcium: 49,
      iron: 2.9,
      vitaminA: 27,
      vitaminC: 1.3,
      vitaminD: 0,
    },
    description: 'Cooked chickpeas',
  },
  {
    name: 'Kidney Beans',
    category: 'Legumes',
    servingSize: 100,
    servingUnit: 'grams',
    nutrition: {
      calories: 127,
      protein: 8.7,
      carbs: 23,
      fat: 0.5,
      fiber: 6.4,
      sugar: 0.3,
      sodium: 2,
      calcium: 28,
      iron: 2.9,
      vitaminA: 0,
      vitaminC: 1.2,
      vitaminD: 0,
    },
    description: 'Cooked kidney beans',
  },
  {
    name: 'Tofu',
    category: 'Legumes',
    servingSize: 100,
    servingUnit: 'grams',
    nutrition: {
      calories: 76,
      protein: 8,
      carbs: 1.9,
      fat: 4.8,
      fiber: 0.3,
      sugar: 0.7,
      sodium: 7,
      calcium: 350,
      iron: 5.4,
      vitaminA: 85,
      vitaminC: 0.1,
      vitaminD: 0,
    },
    description: 'Firm tofu',
  },

  // SNACKS & OTHERS
  {
    name: 'Dark Chocolate (70-85%)',
    category: 'Snacks',
    servingSize: 28,
    servingUnit: 'grams',
    nutrition: {
      calories: 170,
      protein: 2.2,
      carbs: 13,
      fat: 12,
      fiber: 3.1,
      sugar: 6.8,
      sodium: 6,
      calcium: 20,
      iron: 3.4,
      vitaminA: 14,
      vitaminC: 0,
      vitaminD: 0,
    },
    description: 'Dark chocolate',
  },
  {
    name: 'Honey',
    category: 'Snacks',
    servingSize: 21,
    servingUnit: 'grams',
    nutrition: {
      calories: 64,
      protein: 0.1,
      carbs: 17,
      fat: 0,
      fiber: 0,
      sugar: 17,
      sodium: 1,
      calcium: 1,
      iron: 0.1,
      vitaminA: 0,
      vitaminC: 0.1,
      vitaminD: 0,
    },
    description: 'Pure honey',
  },
  {
    name: 'Olive Oil',
    category: 'Oils & Fats',
    servingSize: 14,
    servingUnit: 'grams',
    nutrition: {
      calories: 119,
      protein: 0,
      carbs: 0,
      fat: 14,
      fiber: 0,
      sugar: 0,
      sodium: 0,
      calcium: 0,
      iron: 0.1,
      vitaminA: 0,
      vitaminC: 0,
      vitaminD: 0,
    },
    description: 'Extra virgin olive oil',
  },
  {
    name: 'Coconut Oil',
    category: 'Oils & Fats',
    servingSize: 14,
    servingUnit: 'grams',
    nutrition: {
      calories: 121,
      protein: 0,
      carbs: 0,
      fat: 14,
      fiber: 0,
      sugar: 0,
      sodium: 0,
      calcium: 0,
      iron: 0,
      vitaminA: 0,
      vitaminC: 0,
      vitaminD: 0,
    },
    description: 'Virgin coconut oil',
  },
  {
    name: 'Butter',
    category: 'Oils & Fats',
    servingSize: 14,
    servingUnit: 'grams',
    nutrition: {
      calories: 102,
      protein: 0.1,
      carbs: 0,
      fat: 12,
      fiber: 0,
      sugar: 0,
      sodium: 91,
      calcium: 3,
      iron: 0,
      vitaminA: 355,
      vitaminC: 0,
      vitaminD: 0.2,
    },
    description: 'Salted butter',
  },
];

// const seedComprehensiveFoods = async () => {
//   try {
//     const mongoURI = process.env.MONGODB_URI || 'mongodb://localhost:27017/healthcare';
//     await mongoose.connect(mongoURI);
//     console.log('✅ Connected to MongoDB');

//     // Clear existing foods
//     await Food.deleteMany({});
//     console.log('🗑️  Cleared existing foods');

//     // Insert comprehensive foods
//     await Food.insertMany(comprehensiveFoods);
//     console.log(`✅ Inserted ${comprehensiveFoods.length} foods into database`);

//     // Show summary by category
//     const categories = await Food.aggregate([
//       { $group: { _id: '$category', count: { $sum: 1 } } },
//       { $sort: { _id: 1 } },
//     ]);

//     console.log('\n📊 Foods by Category:');
//     categories.forEach((cat) => {
//       console.log(`   ${cat._id}: ${cat.count} items`);
//     });

//     await mongoose.connection.close();
//     console.log('\n👋 Database connection closed');
//     process.exit(0);
//   } catch (error) {
//     console.error('❌ Error seeding foods:', error);
//     process.exit(1);
//   }
// };
