import mongoose from 'mongoose';
import dotenv from 'dotenv';
import Food from '../models/Food.model';

dotenv.config();

const sampleFoods = [
  {
    name: 'Chicken Breast',
    category: 'Protein',
    servingSize: 100,
    servingUnit: 'grams',
    nutrition: {
      calories: 165,
      protein: 31,
      carbs: 0,
      fat: 3.6,
      fiber: 0,
      sugar: 0,
      sodium: 74,
      calcium: 15,
      iron: 1,
      vitaminA: 21,
      vitaminC: 0,
      vitaminD: 0.1,
    },
    description: 'Skinless, boneless chicken breast',
  },
  {
    name: 'Brown Rice',
    category: 'Grains',
    servingSize: 100,
    servingUnit: 'grams',
    nutrition: {
      calories: 112,
      protein: 2.6,
      carbs: 24,
      fat: 0.9,
      fiber: 1.8,
      sugar: 0.4,
      sodium: 5,
      calcium: 10,
      iron: 0.4,
      vitaminA: 0,
      vitaminC: 0,
      vitaminD: 0,
    },
    description: 'Cooked brown rice',
  },
  {
    name: 'Broccoli',
    category: 'Vegetables',
    servingSize: 100,
    servingUnit: 'grams',
    nutrition: {
      calories: 34,
      protein: 2.8,
      carbs: 7,
      fat: 0.4,
      fiber: 2.6,
      sugar: 1.7,
      sodium: 33,
      calcium: 47,
      iron: 0.7,
      vitaminA: 623,
      vitaminC: 89,
      vitaminD: 0,
    },
    description: 'Fresh broccoli',
  },
  {
    name: 'Salmon',
    category: 'Protein',
    servingSize: 100,
    servingUnit: 'grams',
    nutrition: {
      calories: 208,
      protein: 20,
      carbs: 0,
      fat: 13,
      fiber: 0,
      sugar: 0,
      sodium: 59,
      calcium: 9,
      iron: 0.3,
      vitaminA: 40,
      vitaminC: 0,
      vitaminD: 11,
    },
    description: 'Atlantic salmon',
  },
  {
    name: 'Greek Yogurt',
    category: 'Dairy',
    servingSize: 100,
    servingUnit: 'grams',
    nutrition: {
      calories: 59,
      protein: 10,
      carbs: 3.6,
      fat: 0.4,
      fiber: 0,
      sugar: 3.2,
      sodium: 36,
      calcium: 110,
      iron: 0,
      vitaminA: 0,
      vitaminC: 0.8,
      vitaminD: 0,
    },
    description: 'Plain, non-fat Greek yogurt',
  },
  {
    name: 'Banana',
    category: 'Fruits',
    servingSize: 100,
    servingUnit: 'grams',
    nutrition: {
      calories: 89,
      protein: 1.1,
      carbs: 23,
      fat: 0.3,
      fiber: 2.6,
      sugar: 12,
      sodium: 1,
      calcium: 5,
      iron: 0.3,
      vitaminA: 64,
      vitaminC: 8.7,
      vitaminD: 0,
    },
    description: 'Fresh banana',
  },
  {
    name: 'Almonds',
    category: 'Nuts & Seeds',
    servingSize: 28,
    servingUnit: 'grams',
    nutrition: {
      calories: 164,
      protein: 6,
      carbs: 6,
      fat: 14,
      fiber: 3.5,
      sugar: 1.2,
      sodium: 0,
      calcium: 76,
      iron: 1,
      vitaminA: 0,
      vitaminC: 0,
      vitaminD: 0,
    },
    description: 'Raw almonds',
  },
  {
    name: 'Sweet Potato',
    category: 'Vegetables',
    servingSize: 100,
    servingUnit: 'grams',
    nutrition: {
      calories: 86,
      protein: 1.6,
      carbs: 20,
      fat: 0.1,
      fiber: 3,
      sugar: 4.2,
      sodium: 55,
      calcium: 30,
      iron: 0.6,
      vitaminA: 14187,
      vitaminC: 2.4,
      vitaminD: 0,
    },
    description: 'Baked sweet potato',
  },
  {
    name: 'Eggs',
    category: 'Protein',
    servingSize: 50,
    servingUnit: 'grams',
    nutrition: {
      calories: 72,
      protein: 6,
      carbs: 0.4,
      fat: 5,
      fiber: 0,
      sugar: 0.2,
      sodium: 71,
      calcium: 28,
      iron: 0.9,
      vitaminA: 270,
      vitaminC: 0,
      vitaminD: 2,
    },
    description: 'Large egg',
  },
  {
    name: 'Quinoa',
    category: 'Grains',
    servingSize: 100,
    servingUnit: 'grams',
    nutrition: {
      calories: 120,
      protein: 4.4,
      carbs: 21,
      fat: 1.9,
      fiber: 2.8,
      sugar: 0.9,
      sodium: 7,
      calcium: 17,
      iron: 1.5,
      vitaminA: 5,
      vitaminC: 0,
      vitaminD: 0,
    },
    description: 'Cooked quinoa',
  },
  {
    name: 'Spinach',
    category: 'Vegetables',
    servingSize: 100,
    servingUnit: 'grams',
    nutrition: {
      calories: 23,
      protein: 2.9,
      carbs: 3.6,
      fat: 0.4,
      fiber: 2.2,
      sugar: 0.4,
      sodium: 79,
      calcium: 99,
      iron: 2.7,
      vitaminA: 9377,
      vitaminC: 28,
      vitaminD: 0,
    },
    description: 'Fresh spinach',
  },
  {
    name: 'Avocado',
    category: 'Fruits',
    servingSize: 100,
    servingUnit: 'grams',
    nutrition: {
      calories: 160,
      protein: 2,
      carbs: 9,
      fat: 15,
      fiber: 7,
      sugar: 0.7,
      sodium: 7,
      calcium: 12,
      iron: 0.6,
      vitaminA: 146,
      vitaminC: 10,
      vitaminD: 0,
    },
    description: 'Fresh avocado',
  },
  {
    name: 'Oatmeal',
    category: 'Grains',
    servingSize: 100,
    servingUnit: 'grams',
    nutrition: {
      calories: 71,
      protein: 2.5,
      carbs: 12,
      fat: 1.5,
      fiber: 1.7,
      sugar: 0.3,
      sodium: 49,
      calcium: 9,
      iron: 1,
      vitaminA: 0,
      vitaminC: 0,
      vitaminD: 0,
    },
    description: 'Cooked oatmeal',
  },
  {
    name: 'Apple',
    category: 'Fruits',
    servingSize: 100,
    servingUnit: 'grams',
    nutrition: {
      calories: 52,
      protein: 0.3,
      carbs: 14,
      fat: 0.2,
      fiber: 2.4,
      sugar: 10,
      sodium: 1,
      calcium: 6,
      iron: 0.1,
      vitaminA: 54,
      vitaminC: 4.6,
      vitaminD: 0,
    },
    description: 'Fresh apple',
  },
  {
    name: 'Lentils',
    category: 'Legumes',
    servingSize: 100,
    servingUnit: 'grams',
    nutrition: {
      calories: 116,
      protein: 9,
      carbs: 20,
      fat: 0.4,
      fiber: 7.9,
      sugar: 1.8,
      sodium: 2,
      calcium: 19,
      iron: 3.3,
      vitaminA: 8,
      vitaminC: 1.5,
      vitaminD: 0,
    },
    description: 'Cooked lentils',
  },
];

const seedFoods = async () => {
  try {
    const mongoURI = process.env.MONGODB_URI || 'mongodb://localhost:27017/healthcare';
    await mongoose.connect(mongoURI);
    console.log('✅ Connected to MongoDB');

    // Clear existing foods
    await Food.deleteMany({});
    console.log('🗑️  Cleared existing foods');

    // Insert sample foods
    await Food.insertMany(sampleFoods);
    console.log(`✅ Inserted ${sampleFoods.length} sample foods`);

    await mongoose.connection.close();
    console.log('👋 Database connection closed');
    process.exit(0);
  } catch (error) {
    console.error('❌ Error seeding foods:', error);
    process.exit(1);
  }
};

seedFoods();
